config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    ]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/<int:photo_pk>/delete/",
         views.delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/",
         views.EditPhotoView.as_view(), name="edit-photo"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/delete/", views.delete_room, name="delete-room"),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complete_verification,
         name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block page_title %}{% endblock page_title %}ABclone</title>
  </head>
  <body class="text-gray-800 mt-24 font-light">
    {% include 'partials/messages.html' %}
    <header class="container max-w-full inset-0 flex item-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white">
        <div class="flex items-center w-1/3">
          <a href="{% url "core:home" %}" class="mr-6">
            <img class="w-8" src="{% static 'img/logo.png' %}">
          </a>
        
          {% block search-bar %}
            <form method="get" action="{% url "rooms:search" %}" class="w-9/12">
              <input class="search-box border px-5 w-full font-medium tet-gray-900 placeholder-gray-600 py-3 rounded-sm w-64 shadow-md hover:shadow-lg focus:outline-none" name="city" placeholder="{% trans 'Search by City' %}">
            </form>
          {% endblock search-bar %}
        </div>
        {% include 'partials/nav.html' %}
    </header>

    {% block content %}
    {% endblock content %}

    {% include "partials/footer.html" %}
    <script>
      const langSelect = document.getElementById("js-lang");
      const handleLangChange = () => {
        const selected = langSelect.value;
        fetch(`{% url 'users:switch-language' %}?lang=${selected}`).then(() => window.location.reload());
      }
      langSelect.addEventListener("change", handleLangChange);
    </script>
  </body>
</html>